Exploring task unaware vs aware BTE and generalization error experiment
neurodata/ProgLearn pull request #517
Opened 2021-12-08 21:47 UTC by kfenggg

#### Reference issue
Issue [42](https://github.com/neurodata/ProgLearn/issues/42)

#### Type of change
Added a jupyter notebook and a functions file for the notebook.

#### What does this implement/fix?
This experiment lays the groundwork for implementing a task oblivious learner in proglearn. It explores how sample size affects hyppo k sample test dcorr xor vs rxor p-values at varying angles of rotation. Also, it compares BTE and generalization error of xor with task aware and oblivious learners when introduced with rxor at varying angles of rotation. 

#### Additional information
NDD 2021

2021-12-09 14:11 UTC, PSSF23 requested changes
- Remove unnecessary imports from function file. If it's not used do not import it.
- Add notebook name to `docs/experiments.rst` for the website to render it. Then check to see if it conforms with guidelines on website.

2021-12-09 16:58 UTC, kfenggg commented
@PSSF23 fixed!

2021-12-11 14:33 UTC, PSSF23 reviewed
I need to check preview but it should be good.

2021-12-22 14:25 UTC, PSSF23 approved these changes

2021-12-22 14:26 UTC, merged